name: ðŸ“¦ Build macOS DMG

on:
  workflow_run:
    workflows: ["ðŸš€ Auto Release"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest

    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ðŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ðŸ“¦ Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: ðŸº Install MongoDB Database Tools
        run: |
          brew tap mongodb/brew
          brew install mongodb-database-tools

      - name: ðŸ— Build App
        run: |
          source venv/bin/activate
          pyinstaller --windowed --name MongoVault run.py

      # ðŸ” Get latest tag created by release-please
      - name: ðŸ” Get Latest Tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: ðŸ“¦ Install create-dmg
        run: brew install create-dmg

      - name: ðŸ“¦ Create DMG
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}

          create-dmg \
            --volname "MongoVault" \
            --window-size 600 400 \
            --app-drop-link 450 200 \
            MongoVault-${TAG}.dmg \
            dist/MongoVault.app

      - name: ðŸš€ Upload DMG to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: MongoVault-${{ steps.get_tag.outputs.tag }}.dmg
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
